version: '2.1'
services:
  mysql:
    container_name: mysql
    image: mysql
    restart: always
    hostname: mysql
    ports:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - /data/mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  memcached:
    container_name: memcache
    image: memcached
    restart: always
    hostname: memcached
    links:
      - mysql
    ports:
      - 11211
    healthcheck:
      test: echo stats | nc 127.0.0.1 11211
      interval: 10s
      retries: 60

  application:
    
    build:
      context: application
      dockerfile: Dockerfile
    hostname: nodejs
    links:
      - memcached
      - mysql
    ports:
     - 5000
    healthcheck:
      test: ["CMD", "curl" ,"http://localhost:8080" ]
      timeout: 20s
      retries: 10 

  nginx-web:
    container_name: mginx
    image: nginx
    restart: always
    hostname: nginx
    links:
      - application
    ports:
      - 80
    healthcheck:
      test: ["CMD", "curl" ,"http://localhost:8080" ]
      timeout: 20s
      retries: 10
